name: download bilibili audio
inputs:
  bvid:
    description: "Bilibili bvid"
    required: true
  bili-proxy:
    description: "bili-proxy-host"
    required: true
  sessdata:
    description: "bili sessdata"
    required: false
outputs:
  filename:
    description: 'downloaded filename in artifact'
    value: ${{ fromJSON(steps.bili.outputs.video).bvid }}.mp3
runs:
  using: "composite"
  steps:
    - name: Setup FFmpeg
      uses: AnimMouse/setup-ffmpeg@v1
    - name: get and download video
      id: bili
      uses: ktKongTong/bili-action@v0.2.11
      with:
        bvid: ${{ inputs.bvid }}
        proxy-stream-host: ${{ inputs.bili-proxy }}
        sessdata: ${{ inputs.sessdata }}
        audio: true
        audio-file-template: "output/{bvid}.mp4"
    - name: convert to mp3
      shell: bash
      run: ffmpeg -i output/${{ inputs.bvid }}.mp4 -ar 16000 output/${{ inputs.bvid }}.mp3
    - name: Upload output.mp3
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.bvid }}.mp3
        path: output/${{ inputs.bvid }}.mp3
        if-no-files-found: error
        retention-days: 10