name: stt-gemini
on:
  workflow_dispatch:
    inputs:
      bvid:
        description: 'Bilibili bvid'
        required: false
      prompt:
        description: 'prompt'
        default: ''
        required: false
      model:
        description: 'gemini model'
        type: choice
        default: "gemini-2.0-pro-exp-02-05"
        options:
          - 'gemini-2.0-pro-exp-02-05'
          - 'gemini-2.0-flash'
      category:
        description: 'category'
        type: choice
        options:
          - btnews
          - commercial
          - opinion
        required: false
  schedule:
    - cron: '0 13 * * *'
      # 21:00 in CN
jobs:
  fetch-audio:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup FFmpeg
        uses: AnimMouse/setup-ffmpeg@v1
      - name: set input
        id: set-input
        env: 
          bvid: ${{ inputs.bvid }}
          category: ${{ inputs.category }}
        shell: bash
        run: |
          bash ${GITHUB_WORKSPACE}/.github/scripts/set-input.sh
      - name: bili-action
        id: bili-meta
        uses: ktKongTong/bili-action@v0.2.4
        with: 
          bvid: ${{ inputs.bvid }}
          mid: ${{ steps.set-input.outputs.mid }}
          keyword: ${{ steps.set-input.outputs.keyword }}
      - name: set output to json
        run: | 
          echo '${{ steps.bili-meta.outputs.video }}' > tmp.json
      - name: calc-vars
        id: calc-vars
        run: |
          bash ${GITHUB_WORKSPACE}/.github/scripts/title-parse.sh tmp.json
      - name: bili-action
        id: bili
        if: ${{ steps.calc-vars.outputs.exist != 'true' }}
        uses: ktKongTong/bili-action@v0.2.4
        with: 
          proxy-stream-host: ${{ secrets.BILI_STREAM_PROXY }}
          bvid: ${{ steps.bili-meta.bvid }}
          audio: true
          audio-file-template: 'output/{bvid}.mp4'
      - name: convert to mp3
        if: ${{ steps.calc-vars.outputs.exist != 'true' }}
        run: ffmpeg -i output/${{ steps.bili.outputs.bvid }}.mp4 -ar 16000 output/${{ steps.bili.outputs.bvid }}.mp3
      - name: Upload output.mp3
        uses: actions/upload-artifact@v4
        if: ${{ steps.calc-vars.outputs.exist != 'true' }}
        with:
          name: output.mp3
          path: output/${{ steps.bili.outputs.bvid }}.mp3
          if-no-files-found: error
          retention-days: 1
      - name: gemini-action
        uses: ktKongTong/gemini-action@v0.2.0
        id: gemini-stt
        if: ${{ steps.calc-vars.outputs.exist != 'true' }}
        with: 
          token: ${{ secrets.GEMINI_TOKEN }}
          model: ${{inputs.model}}
          file-path: output/${{ steps.bili.outputs.bvid }}.mp3
          prompt: |
            下面是一段音频，请识别为文本。不要返回额外的内容。
            拆分为合适的段落，并适当的加上标点符号标记。
            段落与段落之间请用两个换行符号分割，段落不宜太松散，也不宜太紧凑。
            请一定不要对原文进行较大幅度的删改、任何删改请务必使用~~~进行标识。
            此外，可能其中部分内容属于不相关的广告部分，请在对应段落前后通过 @@@ 进行标识。
            ${{ inputs.prompt }}
          file-mime: audio/mp3
      - name: show result
        if: ${{ steps.calc-vars.outputs.exist != 'true' }}
        run: |
          echo "${{steps.gemini-stt.outputs.output}}" > output.md
          cat output.md
      - name: Upload output.md
        if: ${{ steps.calc-vars.outputs.exist != 'true' }}
        uses: actions/upload-artifact@v4
        with:
          name: output.md
          path: output.md
          if-no-files-found: error
          retention-days: 1
      - name: createHead
        if: ${{ steps.calc-vars.outputs.exist != 'true' }}
        run: |
          echo '---
          title: ${{steps.bili.outputs.title }}
          description: ${{steps.bili.outputs.title }}
          tag: []
          date: ${{steps.bili.outputs.pubdate }}
          bvid: ${{steps.bili.outputs.bvid }}
          ---
          ' >> tmp.md
          mkdir -p ${{ steps.calc-vars.outputs.path }}
          cat output.md >> tmp.md
          mv tmp.md ${{ steps.calc-vars.outputs.filepath }}
          
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v5
        if: ${{ steps.calc-vars.outputs.exist != 'true' }}
        with:
          token: ${{ secrets.PAT }}
          commit-message: ":memo: new docs ${{ steps.bili.outputs.title }}"
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          delete-branch: true
          branch: fetch/${{ steps.bili.outputs.bvid }}
          title: ":memo: new docs ${{ steps.bili.outputs.title }}"
          add-paths: |
            docs/**/*.md
            images/**/*.webp
          base: master
          body: |
            ":memo: new docs ${{ steps.bili.outputs.title }}"
            - Auto-generated by action: [create-pull-request](https://github.com/peter-evans/create-pull-request) with dify
          labels: |
            automated pr
          draft: false
